### ISSUE TITLE
How to configure several retires with throttle

### ISSUE THREAD

**Issue by arlac77** [VoiceNGO/promise-repeat#1]
With the following options I expected 5 retries with a 1000ms delay in between.
But I got a delayed 1st. retry and then the 4 following retries where without visible delay.
Is it required to use the throttleFn() even in simple cases ?

``` javascript
{
maxAttempts: 5,
minTimeout: 1000,
maxTimeout: 6000,
throttle: 1000
}
```

**Comment by MarkKahn** [comment]
re-wrote lib, fixex
